# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75cedfdb3560a57dfa0d19717557caa36fec63ac928b6f180a9b5509dc02e1230607e510d42b3ea8ed6a0fa23c35d4b38eb774f1f64726fbc3aef5fc16ffbfad

test:
  secret_key_base: 75a6e6d0e2aef3fe532aee7ab6c9b13588b07cc6b0495711d16ae8b29979bfdf21113e1d32bab749953a92231ff2795bd8d69be92423dc8a83584f3f2466b7b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
